---
title: "Ruben C. Arslan"
bibliography: bibliography.bibtex
nocite: |
 @R @rmarkdown @distill @knitr @devtools @lme4 @rAltmetric @rcrossref @RISmed @rscopus @tidyverse @rio @cowplot @broom @rbokeh @DT @dplyr @ggbeeswarm @ggplot2 @Hmisc @httr @lubridate @formr @stringdist @brms @car @reshape2 @stringr @zoo @highcharter @ggvis @codebook @haven @UpSetR @forcats @coefplot @effects @lmerTest
description: |
  About this page.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

This page is intended to help me organize and document some of my (side) projects, especially my nontraditional publications, like preprints, blog posts, supplementary websites, software, tutorials, workshops and outreach slides, and small simulations.
You can find my traditional publications on my [Google Scholar profile](https://scholar.google.com/citations?user=X6fXzMcAAAAJ&hl=en) for now.
The blog's name (One lives only to make blunders) is taken from this famous letter from [Darwin to Lyell](https://www.darwinproject.ac.uk/letter/DCP-LETT-3272.xml).

This website was generated using these great tools @R @rmarkdown @knitr @distill

## Privacy Policy
Effective date: September 23, 2018

### Embedded Content
Articles on this site may include embedded content (e.g. videos, images, articles, etc.). Embedded content from other websites behaves in the exact same way as if the visitor has visited the other website.

These websites may collect data about you, use cookies, embed additional third-party tracking, and monitor your interaction with that embedded content, including tracing your interaction with the embedded content if you have an account and are logged in to that website.


### Service Providers
We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.

These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.

#### Analytics
We may use third-party Service Providers to monitor and analyze the use of our Service.

##### Google Analytics

Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.

You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js, and dc.js) from sharing information with Google Analytics about visits activity.

For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: <a href="https://policies.google.com/privacy?hl=en">https://policies.google.com/privacy?hl=en</a>


### Links To Other Sites
Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.

We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.



### Changes To This Privacy Policy
We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.

If you have any questions about this Privacy Policy, please contact me by email ruben.arslan@gmail.com
          
