---
title: "Genetische Analysen implizieren keineswegs Unmenschlichkeit – im Gegenteil"
description: |
  Genetische Unterschiede sind ein Argument für den Sozialstaat
author:
  - name: "Ruben C. Arslan"
    url: https://rubenarslan.github.io
    affiliation_url: https://www.mpib-berlin.mpg.de/en/staff/ruben-arslan
    affiliation: "Center for Adaptive Rationality, Max Planck Institute for Human Development, Berlin" 
  - name: "Gert G. Wagner"
    affiliation: "Max Planck Institute for Human Development, Berlin, German Institute for Economic Research (DIW Berlin)" 
  - name: "Philipp Köllinger"
    affiliation: "Free University Amsterdam (VU), German Institute for Economic Research (DIW Berlin)" 
date: 01-21-2019
output:
  radix::radix_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<small>My colleagues and I wrote the following (in German) to announce the release of a new GWAS on risk preferences.
We also respond to an article in the Sueddeutsche Zeitung on the heritability of intelligence that we thought was misleading on
some major points. Maybe some of those misconceptions and the desire to reject genetic explanations for individual differences 
come from an assumption that genetic research must lead to a "survival of the fittest" mentality. We disagree. A shorter
version appeared in the Sueddeutsche Zeitung today.</small>

_gekürzt erschienen unter dem Titel [„Argumente für mehr Solidarität“ in der Süddeutschen Zeitung](https://www.sueddeutsche.de/wirtschaft/forum-argumente-fuer-mehr-solidaritaet-1.4295164) am 21. Januar 2019, S. 18_

<small>Ruben C. Arslan ist Psychologe am Max Planck Institut für Bildungsforschung, Berlin, wo auch der Ökonom Gert G. Wagner tätig ist. Philipp Köllinger ist Professor für Genom-Ökonomie an der Freien Universität Amsterdam. Köllinger und Wagner sind auch Research Fellows am Deutschen Institut für Wirtschaftsforschung (DIW Berlin). Alle Autoren waren 2014 bis 2017 Mitglied in der Forschergruppe „Genetic and Social Causes of Life Chances“ am Zentrum für interdisziplinäre Forschung (ZiF) der Universität Bielefeld.</small>

Mitte Januar 2019 ist in der Fachzeitschrift Nature Genetics ein [Aufsatz zu den genetischen Grundlagen der menschlichen Risikobereitschaft](https://doi.org/10.1038/s41588-018-0309-3) online gegangen, an dem zwei der Autoren dieses Beitrags beteiligt sind (u.a. auf Basis der Daten der Berliner Altersstudie). Im Genom von über einer Million Menschen, deren Daten analysiert wurden, wurden 124 Stellen gefunden, die die Risikobereitschaft vorhersagen, die von den analysierten Befragten angegeben wurde. Außerdem wurden entsprechende molekulargenetische Zusammenhänge mit tatsächlichem Verhalten, etwa Rauchen und Trinken, gefunden. Aber von der enormen Streuung der menschlichen Risikobereitschaft kann durch einzelne Gen-Varianten fast nichts statistisch erklärt werden. Die wichtigste Variante erklärt nur 0,02 Prozent der Streuung – statistisch signifikant, also kein reiner Zufall, aber trotzdem wird so gut wie kein Unterschied in der Risikobereitschaft durch eine Stelle im Genom erklärt.

Durch die Betrachtung von größeren Bereichen des Genoms, die Millionen von einzelnen Gen-Buchstaben enthalten (aus über sechs Milliarden Buchstaben, aus denen ein menschliches Genom besteht), konnten immerhin 1,6 Prozent der Streuung statistisch aufgeklärt werden. Die winzigen Effekte vieler Stellen im Genom summieren sich. Aber auch nun würde es sich nicht lohnen die Speichelproben von Investmentbankern zu analysieren, um herauszufinden, wie risikobereit sie sind. In der Studie wird [ausdrücklich festgestellt](https://www.thessgac.org/faqs), dass das Ergebnis der Analyse sich nicht eignet um die Risikobereitschaft eines einzelnen Menschen vorherzusagen – der Prognosefehler wäre viel zu hoch. Wozu also der ganze Aufwand? Was kann man aus solchen Genom-Analysen schlussfolgern und was nicht? Sind derartige genetische Analysen nicht von Grund auf menschenunwürdig und führen in moralische Abgründe? „Nein“ ist unsere im folgenden begründete Antwort. Genetische Erkenntnisse können sogar zur Menschenwürde beitragen, da sie gute Argumente liefern für Solidarität und für Bestrebungen hin zu mehr Chancengleichheit in unserer Gesellschaft.

Erst einmal ist gewissermaßen „innerwissenschaftlich“ festzuhalten, dass die erfolgreiche Erklärung von psychologischen Unterschieden durch molekulargenetisch gemessene Unterschiede die bereits länger bestehenden Kernergebnisse der sogenannten Verhaltensgenetik bestätigt. Diese Disziplin berechnet auf Basis von Studien zur Ähnlichkeit von beispielsweise adoptierten Geschwistern oder separat aufgewachsenen eineiigen Zwillingen die Wichtigkeit von genetischen Unterschieden gezeigt. Demnach sind im statistischen Mittel genetische Unterschiede innerhalb von Familien maßgeblicher für Persönlichkeit und kognitive Leistungsfähigkeit als Unterschiede in der Erziehung zwischen Familien. Eltern mit mehreren Kindern wissen auch wie unterschiedlich ihre Kinder sein können, obwohl ihre familiäre und soziale Umgebung ja ähnlich ist. Aber weder die menschliche Erfahrung und erst recht nicht die neuartigen genetischen Analysen können die Kritiker der Humangenetik überzeugen.

Kürzlich bestritt zum Beispiel kürzlich der Regensburger Psychologieprofessor Christof Kuhbandner in der [Süddeutschen Zeitung (14. Dezember 2018)](https://www.sueddeutsche.de/bildung/paedagogik-intelligenz-ist-nicht-angeboren-1.4245200), dass Intelligenz überhaupt in einem nennenswerten Ausmaß erblich sei – und legt nahe, dass Kinder mehr lernen, wenn man sie glauben lässt, dass an Intelligenz nichts Angeborenes ist. Er kritisiert die Aussagekraft der Verhaltensgenetik und prognostiziert, dass das Genom niemals mehr als etwa vier Prozent der Streuung von gemessener Intelligenz vorhersagen können wird. In der Tat sind es aber bereits jetzt bis zu 10 Prozent, die sich molekulargenetisch erklären lassen, d. h. durch die Betrachtung des Genoms im Detail – Buchstabe für Buchstabe. Und selbst wenn es wirklich „nur“ vier Prozent wären, wäre das eine ganze Menge. Wenn jemand bei allen gefundenen Genen die intelligenzzuträglichen Varianten hätte, entspräche das dem Effekt eines zusätzlichen Schuljahrs.
Und Kuhbandner unterschätzt die genetische Prognostik systematisch. Er hat zwar recht, dass Gen-Varianten, die mit Hilfe von immer größeren Stichproben von Menschen gefunden werden, immer weniger an Streuung erklären werden (weil man die größeren Effekte bereits mit kleineren Stichproben gefunden hat), aber das bedeutet nicht, dass deswegen die Analyse nicht lohnt. Denn es werden immer mehr einzelne Gen-Buchstaben gefunden werden, die in ihrem Zusammenwirken sehr wohl mehr erklären werden. Dies zeigen Studien beispielsweise zur Genetik von Körpergröße sehr eindeutig. Für diese Bereiche können wir bereits jetzt ein Viertel der Streuung mit Hilfe tausender Gen- Buchstaben erklärt werden. Forscher nehmen an, dass für den IQ über 30% mit riesengrossen Stichproben von Millionen von Menschen aus den Molekülen des Genoms vorhersagbar sein werden. Auch wenn 30 Prozent übertrieben sein mögen, zeigen die Molekulargenetik, dass angeborene Unterschiede der Intelligenz nicht ganz unwichtig sind. Das heisst aber natürlich nicht, dass deswegen die Schlaueren dies ungehemmt ausnützen können sollten. Wir werden darauf am Ende zurückkommen.

Erziehungswissenschaftler wie auch Kuhbandner argumentieren auf einer pädagogischen Ebene. Sie sagen, dass es für Kinder in der Schule besser sein, wenn man gar nicht von angeborenen Unterschieden spricht. Wir behaupten das genaue Gegenteil. Es wäre offenbar ja unverantwortlich und grausam, von einem Kind mit eingeschränkter kognitiver Leistungsfähigkeit soviel zu erwarten wie vom begabten Geschwisterkind. Genauso wäre es grausam jemandem, der mit Mühe den Schulabschluss geschafft zu empfehlen, doch zum Softwarearchitekten umzuschulen, wenn seine berufliche Tätigkeit wegautomatisiert wird. Die Note von „nicht bestanden“ in „noch nicht bestanden“ zu ändern, wie Kuhbander nahe legt, wird auch kaum helfen – neuere Studien können die von Carol Dweck vermarkteten Erfolge des growth mindset jedenfalls [nicht unabhängig replizieren](https://osf.io/preprints/socarxiv/tsdwy/).

Schule bildet ohne Zweifel, aber sie kann die Effekte genetischer Unterschiede nicht völlig einebnen. Man kann auch Menschen durch „Schulung“ nicht beliebig risikofreudig machen, um mehr Unternehmertum zu haben oder sich einiges an sozialer Sicherung zu ersparen, da risikofreudige Menschen große Einkommensschwankungen klaglos hinnähmen.

Bei der modernen genetischen Forschung, wie sie hier berichtet wird, geht es auch nicht nur darum einzelnen Menschen bessere Therapien bei schweren Krankheiten oder maßgeschneiderte Lehr-Konzepte anzubieten (es bleibt ohnehin abzuwarten was da möglich sein wird). Es geht auch darum, und das mag sich am Ende vielleicht als noch wichtiger erweisen, bestimmte gesellschaftliche Strukturen, die immer wieder in Gefahr geraten zerstört zu werden, besser zu begründen und abzusichern als bislang. Also: Man sollte die Evidenz relevanter genetischer Unterschiede nicht leugnen. Sie bedeutet keineswegs, dass daraus ein „Survival of the Fittest“ als normative Leitlinie für das menschliche Zusammenleben folgen muss. Ganz im Gegenteil! Man kann auch ohne weiteres auch argumentieren, dass Nachteile, die einem Menschen durch seine „genetische Ausstattung“ entstehen, von der Gesellschaft zumindest teilweise kompensiert, vielleicht sogar möglichst weitgehend ausgeglichen werden sollten, da ja niemand was für seine Gene kann und sie mit dazu beitragen an welcher Stelle in der Gesellschaft sich jemand findet. Vielfältigkeit der Menschen ist ein Wert an sich. Genetische Vielfalt erhöht die Anpassungsfähigkeit einer Art und Gene, die heutzutage mit Nachteilen verbunden sind, können sich in Zukunft für die Menschheit als lebenswichtig erweisen. In der Tat orientiert sich unsere Steuer- und Sozialpolitik an diesen Überlegungen – in Deutschland und in vielen Ländern in der Welt. Wir wollen die Menschen nicht gleichmachen, sondern wir wollen Nachteile aller Art, mit denen wir ohne eigene Schuld durch das Leben gehen müssen, soweit es vernünftig ist, kompensieren.

Ein Wirtschaftsphilosoph, John E. Roemer, hat diesen Standpunkt mit seiner Theorie zur Chancengleichheit (Equality of Opportunity) auf den Punkt gebracht: individuelle Anstrengung sollte sich lohnen, aber Unterschiede im Einkommen, die sich aufgrund der Chancen ergeben, die einem die Eltern mitgaben (sowohl genetisch wie sozial), sollten durch Steuern und Transfers ausgeglichen werden. Eine progressive Besteuerung hoher Einkommen einerseits und andererseits Transfers an Menschen, die Probleme haben ein ordentliches Einkommen zu erzielen, machen genau dieses. Natürlich nicht perfekt, aber weit jenseits eines ungebremsten individuellen Egoismus, der un-verdiente Vorteile, die jemand mitbekommen hat, ausnützt. Mit anderen Worten: Da eine günstige genetische Ausstattung im Wortsinne un-verdient ist, können die Analysen, die die Bedeutung der Gene für das menschliche Leben zeigen, die Argumente für einen starken Steuer- und Sozialstaat stärken.
